all:
  children:
    staging:
      hosts:
        lab-devops-ec2:
          ansible_host: 35.180.54.218
          ansible_user: ubuntu
          ansible_ssh_private_key_file: ~/.ssh/lab-devops-key.pem
          ansible_python_interpreter: /usr/bin/python3
